language: python
#In this file, I practice pull requests

sudo: false

install: 
    - pip install doc8
    - npm install -g write-good

script:
    - doc8 README.rst
    - write-good README.rst --so --thereIs --cliches
