language: python

sudo: false

install: 
    - pip install doc8
    - npm install -g write-good
    - npm run serve

script:
    - doc8 README.rst
    - write-good README.rst --so --thereIs --cliches
